version: 2.1

jobs:
    build:
        docker:
            - image: circleci/golang:1.12
        working_directory: /go/src/github.com/pelletier/go-src
        environment:
            TEST_RESULTS: /tmp/test-results
        steps:
            - checkout
            - run: mkdir -p ${TEST_RESULTS}
            - run:
                name: Get tests deps
                command: |
                    go get github.com/jstemmer/go-junit-report
            - run:
                name: Run unit tests
                command: |
                    trap "go-junit-report < ${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
                    go test github.com/pelletier/go-src -race -v | tee ${TEST_RESULTS}/go-test.out
            - store_artifacts:
                path: ${TEST_RESULTS}
                destination: raw-test-output
            - store_test_results:
                path: ${TEST_RESULTS}
