version: 2.1

jobs:
    linux:
        docker:
            - image: circleci/golang:1.12
        working_directory: /go/src/github.com/pelletier/git-src
        environment:
            TEST_RESULTS: /tmp/test-results
        steps:
            - checkout
            - run: mkdir -p ${TEST_RESULTS}
            - run:
                name: Get tests deps
                command: |
                    go get github.com/jstemmer/go-junit-report
            - run:
                name: Run unit tests
                command: |
                    trap "go-junit-report < ${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
                    go test github.com/pelletier/git-src -race -v | tee ${TEST_RESULTS}/go-test.out
            - run:
                name: Build binary linux x64
                command: |
                    export BINS=/tmp/workspace/binaries
                    mkdir -p ${BINS}
                    CGO_ENABLED=0 GOOS=linux go build -o ${BINS}/git-src-linux-x64-master -a -ldflags '-extldflags "-static"' github.com/pelletier/git-src
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - binaries/git-src-linux-x64-master
            - store_test_results:
                path: /tmp/test-results
    release:
        docker:
            - image: circleci/golang:1.12
        steps:
            - attach_workspace:
                at: /tmp/workspace
            - store_artifacts:
                path: /tmp/workspace/binaries
                destination: binaries
            - run: go get github.com/tcnksm/ghr
            - run:
                name: "Publish release to github"
                command: |
                    ghr -t ${GITHUB_TOKEN} -n "Master" -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -prerelease -delete master /tmp/workspace/binaries/

workflows:
    version: 2.1
    build:
        jobs:
            - linux:
                name: "linux_x64"
            - release:
                requires:
                    - linux_x64
                filters:
                    branches:
                        only: master
